### ISSUE TITLE
How to do a simple Resource server config?

### ISSUE THREAD

**Issue by martinrm77** [thomsonreuters/bottle-oauthlib#2]
I'm trying to figure out how to configure a simple resource server in bottle with bottle-oauthlib. I dont need a provider, I have a provider, I just need to make use of the provider and check the integrity and extract the claims from the token.

I can't figure it out from your example - oauthlib documentation dont have any examples either - only when you are creating your own provider.

I suppose you just have to remove some of the functions from the validator?

**Comment by JonathanHuot** [comment]
Hi @martinrm77, `bottle-oauthlib` is only used when you want to write your own custom OAuth2 provider.

You said you already have a provider (Google, Azure, or others), so you want an OAuth2 client. You can check [requests/requests-oauthlib ](https://github.com/requests/requests-oauthlib) to connect to your provider, and you can use [jpadilla/pyjwt](https://github.com/jpadilla/pyjwt) if your provider uses JWT for checking token integrity.

**Comment by martinrm77** [comment]
ok, thank you.

I guess I need a bottle-pyoidc (which does not exist) for making a web application protected by an existing OAUTH Identity provider.

Your documentation just states your module can do it all, and it really does, so Im thinking it must be possible to configure it against an external identity provider.

Thank you for your answer, I will use pyoidc, which can do the job.

**Comment by JonathanHuot** [comment]
Hi @martinrm77, to follow this, I have added a quickstart example around a standalone ResourceServer with bottle-oauthlib. 
I'll probably simplify the code more later.
Cheers
