### ISSUE TITLE
Getting permission denied when trying @app.auth.verify_request Error 403 any hints on what to look for?

### ISSUE THREAD

**Issue by fredclingen** [thomsonreuters/bottle-oauthlib#4]
Expected behavior and actual behavior.
----------

..here..

Steps to reproduce the problem.
----------

..here..

Specifications like the version of the project, operating system.
----------

..here..

**Comment by JonathanHuot** [comment]
Hi @fredclingen, could you paste the `RequestValidator.verify_request`'s content and also the controller/decorator which uses it ?

That would be necessary to understand the problem.
Thanks
